### ISSUE TITLE
CODE RUB: Label Action Build Fix

### ISSUE THREAD

**Issue by glhays** [The-Standard-Organization/ADotNet#115]
Hi @cjdutoit 
The following if statement I added to the SPAL repo build action resolved the Label TypeError issue.
Does this need to be added here so it can be implemented across the galaxies. :)

![image](https://github.com/The-Standard-Organization/ADotNet/assets/42452283/175530de-35af-485a-b63e-c0e9a4d94b12)

**Comment by cjdutoit** [comment]
Fixed in #121
