### ISSUE TITLE
CODE RUB: Move Unit Test Build Files to Folder

### ISSUE THREAD

**Issue by ShriHumrudha** [The-Standard-Organization/ADotNet#21]
<img width="195" alt="image" src="https://user-images.githubusercontent.com/89320816/151722041-2be6fa4d-45c9-4049-967b-cbc5ca42aa11.png">

**Comment by ahmedanwar100** [comment]
I claim this issue @hassanhabib

**Comment by ahmedanwar100** [comment]
@glhays currently nothing

**Comment by glhays** [comment]
Closed via #103
