### ISSUE TITLE
Adding a PublishTask

### ISSUE THREAD

**Issue by mabroukmahdhi** [The-Standard-Organization/ADotNet#37]
Hello,

could you please also add a PublishTask ? Also to deploy a .net core app to a preferred IIS. 

Something like 
```c#
 public class PublishTask : GithubTask
    {
        [YamlMember(Order = 1)]
        public string Run = "dotnet publish .....";
    }
```

**Comment by lohithgn** [comment]
@mabroukmahdhi 

if you asking for `dotnet publish` - i think its already supported. 

If you check the readme.md, there is a real life example to showcase publish task. Here is the code:

```
new DotNetExecutionTask
          {
              DisplayName = "Publish",

              Inputs = new DotNetExecutionTasksInputs
              {
                  Command = Command.publish,
                  PublishWebProjects = true
              }
          }
```

this is internally calling `dotnet publish` and depending on the .net version this will publish code to `bin\debug\<.net version>\publish` folder.

Hope this helps.

**Comment by glhays** [comment]
@hassanhabib  @mabroukmahdhi does this relate in any way to a nuget package publish?
